name: 'Update GitHub Release'
description: 'Update GitHub Release'
author: 'tubone24'
inputs:
  release_name:
    description: 'new release name, if not, take over before name'
    required: false
  body:
    description: 'new body text, if not, take over before text'
    required: false
  draft:
    description: 'new draft, if not, take over before draft'
    required: false
  prerelease:
    description: 'new prerelease, if not, take over prerelease'
    required: false
  is_append_body:
    description: 'If true, append body text, If false, overwrite body text, default is false'
    required: false
  body_path:
    description: 'Path to file with new body text.'
    required: false
outputs:
  id:
    description: 'The ID of the Release'
  html_url:
    description: 'The HTML url of the Release'
  upload_url:
    description: 'The upload url of the Release'
  name:
    description: 'The name of the Release'
  body:
    description: 'The body of the Release'
  published_at:
    description: 'The publish at of the Release'
  tag_name:
    description: 'The tag name of the Release'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'green'
